#Do this when you before you start tmux for the first time
#git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
#prefix + I to reload tmux environment after startup for the first time

# set scroll history to 100,000 lines
set-option -g history-limit 100000

# improve colors
set -g default-terminal 'screen-256color'

set-option -g default-shell /usr/bin/zsh

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.tmux.conf

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-option -g allow-rename off
set -g base-index 1 # start windows numbering at 1

# start pane numbers at 1 to match keyboard order with tmux order
setw -g pane-base-index 1

# renumber windows sequentially after closing any of them
set -g renumber-windows on

setw -g mode-keys vi
bind -T copy-mode-vi "v" send -X begin-selection
bind -T copy-mode-vi "V" send -X rectangle-toggle
bind -T copy-mode-vi "y" send -X copy-selection-and-cancel

# TPM path
set -g @plugin 'tmux-plugins/tpm'

# tmux-resurrect
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'

# for vim
set -g @resurrect-strategy-vim 'session'
# for neovim
set -g @resurrect-strategy-nvim 'session'

set -g @resurrect-capture-pane-contents 'on'

# Initialize TPM (keep this at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
